name: deploy

on:
  push:
    branches: [main] # main 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 打包

      - name: Deploy
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }} # 云服务器的公网地址
          username: ${{ secrets.USERNAME }} # 云服务器的登录用户名
          password: ${{ secrets.PASSWORD }} # 云服务器的登录密码
          port: ${{ secrets.PORT }} # 云服务器的端口
          source: 'dist/' # 这是要复制到云服务器的文件夹名称
          target: '/data/server-dist' # # 打包后的 dist 文件夹将放在 云服务器的文件位置

      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /data/service_file
            sh ./deploy.sh
